owner: paulojoseppe # GitHub username
repo: uptimeValores # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com.br
  - name: ZapVoice.com
    url: https://zapvoice.com
  - name: Rec zappvoice
    url: https://rec.zappvoice.top
    
status-website:
  baseUrl: /uptimeValores # where "repo" is your repository name
  name: Your Status Website
